"""Immutable outputs generated by the baseline tag, never by the port."""

from dataclasses import replace
import hashlib
import json
import os
from pathlib import Path

import numpy as np
import pytest

from audio_fixtures import FIXTURE_NAMES, write_fixture
from metriq_visualizer_core import DEFAULT_PRESETS, analyze_media, build_geometry

GOLDENS = Path(__file__).parent / "goldens" / "audio_v1_10_18"
# Float32 DSP is exact on the platform that generated the goldens (macOS arm64):
# run with METRIQ_STRICT_GOLDENS=1 there. Other platforms differ in FFT/BLAS and
# FFmpeg resampling; measured worst case on Linux with FFmpeg is 0.11% of a
# feature's range, so elsewhere we allow 0.5% of the range (about 4x margin). Features of a silent
# input are numerical dust around zero (about 1e-4, e.g. MFCCs); 1e-3 absolute covers that.
RTOL, ATOL = 1e-7, 1e-8
CROSS_PLATFORM_RANGE_FRACTION = 0.005


def assert_exact(actual, expected, *, err_msg=""):
    if os.environ.get("METRIQ_STRICT_GOLDENS") == "1":
        np.testing.assert_array_equal(actual, expected, err_msg=err_msg)
    else:
        assert_matches(actual, expected, err_msg=err_msg)


def assert_matches(actual, expected, *, err_msg=""):
    actual, expected = np.asarray(actual, dtype=float), np.asarray(expected, dtype=float)
    if os.environ.get("METRIQ_STRICT_GOLDENS") == "1":
        np.testing.assert_allclose(actual, expected, rtol=RTOL, atol=ATOL, err_msg=err_msg)
        return
    spread = float(np.nanmax(expected) - np.nanmin(expected)) if expected.size else 0.0
    np.testing.assert_allclose(actual, expected, rtol=0, atol=max(CROSS_PLATFORM_RANGE_FRACTION * spread, 1e-3), err_msg=err_msg)


def decoded_22050(name):
    """The 22.05 kHz audio the v1.10.18 code produced from the fixture (via FFmpeg, once).

    Using it makes these tests compare our DSP against the saved results on identical samples
    everywhere, independent of the installed FFmpeg's resampler version.
    """
    manifest = json.loads((GOLDENS / "manifest.json").read_text())
    path = GOLDENS / f"decoded_{name}_22050.wav"
    assert hashlib.sha256(path.read_bytes()).hexdigest() == manifest["decoded_22050_sha256"][name]
    return path


@pytest.fixture(params=FIXTURE_NAMES)
def analysis_pair(request, tmp_path):
    name = request.param
    wav = tmp_path / f"{name}.wav"
    write_fixture(wav, name)
    manifest = json.loads((GOLDENS / "manifest.json").read_text())
    assert manifest["tag"] == "baseline-v1.10.18"
    assert hashlib.sha256(wav.read_bytes()).hexdigest() == manifest["fixture_sha256"][name]
    actual = analyze_media(decoded_22050(name), temp_dir=tmp_path / "decode", use_cache=False)
    with np.load(GOLDENS / f"{name}.npz", allow_pickle=False) as archive:
        expected = {key: archive[key] for key in archive.files}
    return actual, expected


def test_every_legacy_feature_and_panel_matches_baseline(analysis_pair):
    actual, expected = analysis_pair
    names = {key for key in expected if not key.startswith("panel_")}
    assert len(names) == 54
    assert names <= actual.features.keys()
    assert actual.times.size == 690
    assert actual.sample_rate == 22050
    assert actual.duration == 8
    for name in sorted(names):
        assert_matches(actual.features[name], expected[name], err_msg=f"Legacy feature: {name}")
    for attribute, golden in (("spectrogram_db", "panel_spectrogram"),
                              ("spectrogram_freqs_hz", "panel_frequencies"),
                              ("chromagram", "panel_chromagram"), ("mfcc", "panel_mfcc")):
        assert_matches(getattr(actual, attribute), expected[golden], err_msg=attribute)
    # RMS drives both point sizing and silence gating. Its legacy Hann-window
    # scaling, zero value, and silence dB floor must survive without drift.
    assert_exact(actual.features["rms"], expected["rms"])
    assert_exact(actual.features["rms_db"], expected["rms_db"])


@pytest.mark.parametrize("name", FIXTURE_NAMES)
@pytest.mark.parametrize("profile", ("native_large", "odd_fft"))
def test_configurable_settings_match_baseline_goldens(name, profile, tmp_path):
    manifest = json.loads((GOLDENS / "manifest.json").read_text())
    settings = manifest["additional_profiles"][profile]
    if settings["sample_rate"] == 22050:
        wav = decoded_22050(name)
    else:  # native rate: FFmpeg only copies the 44.1 kHz fixture, so no resampler is involved
        wav = tmp_path / f"{name}.wav"
        write_fixture(wav, name)
    actual = analyze_media(wav, **settings, temp_dir=tmp_path / "decode", use_cache=False)
    with np.load(GOLDENS / f"{name}_{profile}.npz", allow_pickle=False) as expected:
        assert set(expected.files) <= actual.features.keys()
        for key in expected.files:
            assert_matches(actual.features[key], expected[key], err_msg=f"{profile}: {key}")
        assert_exact(actual.features["rms"], expected["rms"])


@pytest.mark.parametrize("mode", ("raw", "minmax", "zscore"))
def test_saved_formula_geometry_matches_baseline(analysis_pair, mode):
    actual, expected = analysis_pair
    baseline = replace(actual, features={key: value for key, value in expected.items()
                                         if not key.startswith("panel_")})
    presets = [preset for name, preset in DEFAULT_PRESETS.items() if not name.startswith("Table")]
    # Cover note-named chroma, upper MFCC/contrast and all legacy PCA axes too.
    presets.append(dict(x="chroma_A + mfcc_13", y="contrast_7 + pc4", z="pc5 + pc6",
                        color="rms_db", size="rms"))
    for preset in presets:
        arguments = [preset[key] for key in ("x", "y", "z", "color", "size")]
        options = dict(normalize_mode=mode, max_points=128, low_volume_cutoff_db=18)
        old = build_geometry(baseline, *arguments, **options)
        new = build_geometry(actual, *arguments, **options)
        for attribute in ("x_full", "y_full", "z_full", "color_full", "size_full",
                          "size_display_full", "x_plot", "y_plot", "z_plot", "size_plot"):
            assert_matches(getattr(new, attribute), getattr(old, attribute), err_msg=f"{mode}: {attribute}")
        assert_exact(new.active_mask_full, old.active_mask_full)
        assert_exact(new.plot_indices, old.plot_indices)
