"""Immutable outputs generated by the baseline tag, never by the port."""

from dataclasses import replace
import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from audio_fixtures import FIXTURE_NAMES, write_fixture
from metriq_visualizer_core import DEFAULT_PRESETS, analyze_media, build_geometry

GOLDENS = Path(__file__).parent / "goldens" / "audio_v1_10_18"
# Float32 DSP remains exact on the generation platform. Allow small FFT/BLAS
# rounding differences on other platforms; no feature/algorithm exceptions.
RTOL, ATOL = 1e-7, 1e-8


@pytest.fixture(params=FIXTURE_NAMES)
def analysis_pair(request, tmp_path):
    name = request.param
    wav = tmp_path / f"{name}.wav"
    write_fixture(wav, name)
    manifest = json.loads((GOLDENS / "manifest.json").read_text())
    assert manifest["tag"] == "baseline-v1.10.18"
    assert hashlib.sha256(wav.read_bytes()).hexdigest() == manifest["fixture_sha256"][name]
    actual = analyze_media(wav, temp_dir=tmp_path / "decode", use_cache=False)
    with np.load(GOLDENS / f"{name}.npz", allow_pickle=False) as archive:
        expected = {key: archive[key] for key in archive.files}
    return actual, expected


def test_every_legacy_feature_and_panel_matches_baseline(analysis_pair):
    actual, expected = analysis_pair
    names = {key for key in expected if not key.startswith("panel_")}
    assert len(names) == 54
    assert names <= actual.features.keys()
    assert actual.times.size == 690
    assert actual.sample_rate == 22050
    assert actual.duration == 8
    for name in sorted(names):
        np.testing.assert_allclose(actual.features[name], expected[name], rtol=RTOL, atol=ATOL,
                                   err_msg=f"Legacy feature: {name}")
    for attribute, golden in (("spectrogram_db", "panel_spectrogram"),
                              ("spectrogram_freqs_hz", "panel_frequencies"),
                              ("chromagram", "panel_chromagram"), ("mfcc", "panel_mfcc")):
        np.testing.assert_allclose(getattr(actual, attribute), expected[golden], rtol=RTOL, atol=ATOL,
                                   err_msg=attribute)
    # RMS drives both point sizing and silence gating. Its legacy Hann-window
    # scaling, zero value, and silence dB floor must survive without drift.
    np.testing.assert_array_equal(actual.features["rms"], expected["rms"])
    np.testing.assert_array_equal(actual.features["rms_db"], expected["rms_db"])


@pytest.mark.parametrize("name", FIXTURE_NAMES)
@pytest.mark.parametrize("profile", ("native_large", "odd_fft"))
def test_configurable_settings_match_baseline_goldens(name, profile, tmp_path):
    manifest = json.loads((GOLDENS / "manifest.json").read_text())
    settings = manifest["additional_profiles"][profile]
    wav = tmp_path / f"{name}.wav"
    write_fixture(wav, name)
    actual = analyze_media(wav, **settings, temp_dir=tmp_path / "decode", use_cache=False)
    with np.load(GOLDENS / f"{name}_{profile}.npz", allow_pickle=False) as expected:
        assert set(expected.files) <= actual.features.keys()
        for key in expected.files:
            np.testing.assert_allclose(actual.features[key], expected[key], rtol=RTOL, atol=ATOL,
                                       err_msg=f"{profile}: {key}")
        np.testing.assert_array_equal(actual.features["rms"], expected["rms"])


@pytest.mark.parametrize("mode", ("raw", "minmax", "zscore"))
def test_saved_formula_geometry_matches_baseline(analysis_pair, mode):
    actual, expected = analysis_pair
    baseline = replace(actual, features={key: value for key, value in expected.items()
                                         if not key.startswith("panel_")})
    presets = [preset for name, preset in DEFAULT_PRESETS.items() if not name.startswith("Table")]
    # Cover note-named chroma, upper MFCC/contrast and all legacy PCA axes too.
    presets.append(dict(x="chroma_A + mfcc_13", y="contrast_7 + pc4", z="pc5 + pc6",
                        color="rms_db", size="rms"))
    for preset in presets:
        arguments = [preset[key] for key in ("x", "y", "z", "color", "size")]
        options = dict(normalize_mode=mode, max_points=128, low_volume_cutoff_db=18)
        old = build_geometry(baseline, *arguments, **options)
        new = build_geometry(actual, *arguments, **options)
        for attribute in ("x_full", "y_full", "z_full", "color_full", "size_full",
                          "size_display_full", "x_plot", "y_plot", "z_plot", "size_plot"):
            np.testing.assert_allclose(getattr(new, attribute), getattr(old, attribute),
                                       rtol=RTOL, atol=ATOL, err_msg=f"{mode}: {attribute}")
        np.testing.assert_array_equal(new.active_mask_full, old.active_mask_full)
        np.testing.assert_array_equal(new.plot_indices, old.plot_indices)
